"""add_booking_slug_and_hospital_patients

Revision ID: 5e678e9edc95
Revises: 715d731e1ae5
Create Date: 2026-05-05 12:24:58.863486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e678e9edc95'
down_revision: Union[str, Sequence[str], None] = '715d731e1ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'patient_id', name='uq_hospital_patient')
    )
    op.create_index(op.f('ix_hospital_patients_id'), 'hospital_patients', ['id'], unique=False)
    op.add_column('hospitals', sa.Column('booking_slug', sa.String(), nullable=True))
    op.execute("UPDATE hospitals SET booking_slug = CONCAT(LOWER(REGEXP_REPLACE(name, '[^a-zA-Z0-9]', '-', 'g')), '-', id) WHERE booking_slug IS NULL")
    op.alter_column('hospitals', 'booking_slug', nullable=False)
    op.create_index(op.f('ix_hospitals_booking_slug'), 'hospitals', ['booking_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospitals_booking_slug'), table_name='hospitals')
    op.drop_column('hospitals', 'booking_slug')
    op.drop_index(op.f('ix_hospital_patients_id'), table_name='hospital_patients')
    op.drop_table('hospital_patients')
    # ### end Alembic commands ###
