"""hospital_management_system

Revision ID: 715d731e1ae5
Revises: ac1045f93643
Create Date: 2026-05-05 10:30:14.686897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715d731e1ae5'
down_revision: Union[str, Sequence[str], None] = 'ac1045f93643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line1', sa.String(), nullable=False),
    sa.Column('line2', sa.String(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    op.create_index(op.f('ix_addresses_country'), 'addresses', ['country'], unique=False)
    op.create_index(op.f('ix_addresses_district'), 'addresses', ['district'], unique=False)
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_index(op.f('ix_addresses_pincode'), 'addresses', ['pincode'], unique=False)
    op.create_index(op.f('ix_addresses_state'), 'addresses', ['state'], unique=False)
    op.create_table('otp_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_requests_id'), 'otp_requests', ['id'], unique=False)
    op.create_index(op.f('ix_otp_requests_phone_number'), 'otp_requests', ['phone_number'], unique=False)
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('hospital_type', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_email'), 'hospitals', ['email'], unique=True)
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_index(op.f('ix_hospitals_registration_number'), 'hospitals', ['registration_number'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.add_column('appointments', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('appointment_type', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('token_number', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'hospitals', ['hospital_id'], ['id'])
    op.add_column('doctors', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('qualification', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('registration_number', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('address_id', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('doctors', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('doctors', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('doctors', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('doctors', 'specialization',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_doctors_registration_number'), 'doctors', ['registration_number'], unique=True)
    op.create_foreign_key(None, 'doctors', 'addresses', ['address_id'], ['id'])
    op.create_foreign_key(None, 'doctors', 'hospitals', ['hospital_id'], ['id'])
    op.create_foreign_key(None, 'doctors', 'departments', ['department_id'], ['id'])
    op.drop_column('doctors', 'address')
    op.add_column('patients', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('blood_group', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('address_id', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('aadhaar_number', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('abha_id', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.alter_column('patients', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=True)
    op.create_foreign_key(None, 'patients', 'addresses', ['address_id'], ['id'])
    op.drop_column('patients', 'address')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'phone_number')
    op.add_column('patients', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.alter_column('patients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('patients', 'emergency_contact_phone')
    op.drop_column('patients', 'emergency_contact_name')
    op.drop_column('patients', 'abha_id')
    op.drop_column('patients', 'aadhaar_number')
    op.drop_column('patients', 'address_id')
    op.drop_column('patients', 'blood_group')
    op.drop_column('patients', 'gender')
    op.add_column('doctors', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_index(op.f('ix_doctors_registration_number'), table_name='doctors')
    op.alter_column('doctors', 'specialization',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doctors', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doctors', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doctors', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('doctors', 'is_active')
    op.drop_column('doctors', 'address_id')
    op.drop_column('doctors', 'department_id')
    op.drop_column('doctors', 'hospital_id')
    op.drop_column('doctors', 'bio')
    op.drop_column('doctors', 'languages')
    op.drop_column('doctors', 'registration_number')
    op.drop_column('doctors', 'qualification')
    op.drop_column('doctors', 'profile_image_url')
    op.drop_column('doctors', 'gender')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'cancellation_reason')
    op.drop_column('appointments', 'token_number')
    op.drop_column('appointments', 'reason')
    op.drop_column('appointments', 'appointment_type')
    op.drop_column('appointments', 'hospital_id')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_hospitals_registration_number'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_email'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_otp_requests_phone_number'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_id'), table_name='otp_requests')
    op.drop_table('otp_requests')
    op.drop_index(op.f('ix_addresses_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_pincode'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_district'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_country'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
