"""add_hospital_scheduling_settings

Revision ID: 781033e75e72
Revises: 5e678e9edc95
Create Date: 2026-05-05 13:01:43.910485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781033e75e72'
down_revision: Union[str, Sequence[str], None] = '5e678e9edc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('slot_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('hospitals', sa.Column('working_hours_start', sa.Time(), nullable=True))
    op.add_column('hospitals', sa.Column('working_hours_end', sa.Time(), nullable=True))
    op.add_column('hospitals', sa.Column('lunch_break_start', sa.Time(), nullable=True))
    op.add_column('hospitals', sa.Column('lunch_break_end', sa.Time(), nullable=True))
    op.add_column('hospitals', sa.Column('working_days', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'working_days')
    op.drop_column('hospitals', 'lunch_break_end')
    op.drop_column('hospitals', 'lunch_break_start')
    op.drop_column('hospitals', 'working_hours_end')
    op.drop_column('hospitals', 'working_hours_start')
    op.drop_column('hospitals', 'slot_duration_minutes')
    # ### end Alembic commands ###
